location / {
    proxy_pass http://app;
    proxy_set_header X-Authenticated $oidc_authenticated;
    proxy_set_header X-Id-Token $oidc_id_token;
    proxy_set_header X-Access-Token $oidc_access_token;
    proxy_set_header X-UserInfo $oidc_userinfo;
    proxy_set_header X-User-ID $oidc_claim_sub;
    proxy_set_header X-User-Email $oidc_claim_email;
    proxy_set_header X-User-Alg $oidc_claim_alg;
}
