name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions: {}

defaults:
  run:
    shell: sh

jobs:
  test:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - if: ${{ matrix.nginx != 'alpine' }}
        name: Set up step
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y --no-install-recommends
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            ca-certificates \
            cpanminus \
            curl \
            libhiredis-dev \
            libjansson-dev \
            libnginx-mod-http-lua \
            luarocks \
            netcat-openbsd \
            nginx \
            nginx-dev \
            redis
          if [ ! "${nginx_version}" = "ubuntu" ]; then
            sudo apt-get install -y --no-install-recommends \
              libluajit2-5.1-dev
          fi
          sudo luarocks install lua-resty-http
          sudo luarocks install lua-resty-string
          sudo luarocks install lua-resty-openssl
          sudo cpanm -n Test::Nginx
        env:
          nginx_version: ${{ matrix.nginx }}
          DEBIAN_FRONTEND: noninteractive
          PERL_MM_OPT: ''
          PERL_MM_USE_DEFAULT: 1
          PERL5LIB: ''
      - if: ${{ matrix.nginx == 'alpine' }}
        name: Set up step with Alpine
        run: |
          apk upgrade
          apk add \
            bash \
            curl \
            gcc \
            gd-dev \
            geoip-dev \
            git \
            hiredis-dev \
            jansson-dev \
            libxslt-dev \
            linux-headers \
            lua-resty-http \
            lua-resty-openssl \
            make \
            musl-dev \
            nginx \
            nginx-mod-http-lua \
            openssl-dev \
            pcre2-dev \
            perl-dev \
            perl-utils \
            py3-cryptography \
            redis \
            zlib-dev
          # Install only as it conflicts with the openresty package
          apk fetch lua-resty-string
          tar -xzvf ./lua-resty-string-*.apk -C /
          cpan -Ti Test::Nginx
        env:
          PERL_MM_USE_DEFAULT: 1
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          set-safe-directory: true
          submodules: true
          token: ${{ github.token }}
      - if: ${{ matrix.nginx == 'ubuntu' || matrix.nginx == 'alpine' }}
        name: Build with distribution
        run: |
          # Download Nginx
          nginx_version="$(nginx -v 2>&1 | sed -e 's/^[^0-9]*//' -e 's/ .*$//')"
          curl -sL -o "nginx-${nginx_version}.tar.gz" "https://nginx.org/download/nginx-${nginx_version}.tar.gz"
          tar xf "nginx-${nginx_version}.tar.gz"
          cd "nginx-${nginx_version}"
          # Configure option
          opt=$(nginx -V 2>&1 | tail -1 | sed -e 's/configure arguments://' -e 's| --add-dynamic-module=[^ ]*||g')
          with_cc_opt=$(echo "${opt}" | grep -e "--with-cc-opt='[^']*'" -o | sed -e "s/^--with-cc-opt='//" -e "s/'$//")
          with_ld_opt=$(echo "${opt}" | grep -e "--with-ld-opt='[^']*'" -o | sed -e "s/^--with-ld-opt='//" -e "s/'$//")
          opt=$(echo "${opt}" | sed -e "s|--with-cc-opt='[^']*'||" -e "s|--with-ld-opt='[^']*'||" -e 's/--without-engine//')
          # Run build
          # shellcheck disable=SC2086
          ./configure \
            ${opt} \
            --with-cc-opt="${with_cc_opt} -DNGX_HTTP_HEADERS" \
            --with-ld-opt="${with_ld_opt}" \
            --add-dynamic-module=..
          make
          # Copy module
          if [ "${dist}" = "ubuntu" ]; then
            sudo=sudo
          fi
          ${sudo} mkdir -p /usr/lib/nginx/modules
          ${sudo} cp objs/ngx_http_oidc_module.so /usr/lib/nginx/modules/
          ${sudo} mkdir -p /usr/local/sbin
          ${sudo} ln -sfn /usr/sbin/nginx /usr/local/sbin/nginx
        env:
          dist: ${{ matrix.nginx }}
      - if: ${{ matrix.nginx != 'ubuntu' && matrix.nginx != 'alpine' }}
        name: Build with sources
        run: |
          # Download Lua module: 0.10.26
          curl -sL -o nginx-mod-lua.tar.gz https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.26.tar.gz
          tar xf nginx-mod-lua.tar.gz
          # Download NDK module
          curl -sL -o nginx-mod-ndk.tar.gz https://github.com/dvershinin/ngx_devel_kit/archive/refs/tags/v0.3.5.tar.gz
          tar xf nginx-mod-ndk.tar.gz
          # Download Nginx
          curl -sL -o "nginx-${nginx_version}.tar.gz" "https://nginx.org/download/nginx-${nginx_version}.tar.gz"
          tar xf "nginx-${nginx_version}.tar.gz"
          cd "nginx-${nginx_version}"
          # Run build
          ./configure \
            --with-compat \
            --with-debug \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-pcre \
            --with-pcre-jit \
            --add-dynamic-module=../lua-nginx-module-0.10.26 \
            --add-dynamic-module=../ngx_devel_kit-0.3.5 \
            --add-dynamic-module=..
          make -j
          # Copy module
          sudo mkdir -p /usr/lib/nginx/modules
          sudo cp objs/ndk_http_module.so /usr/lib/nginx/modules/
          sudo cp objs/ngx_http_lua_module.so /usr/lib/nginx/modules/
          sudo cp objs/ngx_http_oidc_module.so /usr/lib/nginx/modules/
          sudo cp objs/nginx /usr/local/sbin/
        env:
          nginx_version: ${{ matrix.nginx }}
          LUAJIT_INC: /usr/include/luajit-2.1
          LUAJIT_LIB: /usr/lib/x86_64-linux-gnu
      - name: Test
        run: |
          # nginx
          echo "::group::nginx show version"
          ${TEST_NGINX_BINARY} -V
          echo "::endgroup::"
          # Run IdP stub
          echo "::group::run oidc stub"
          curl -sfSLO "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz"
          tar -zxf "oras_${ORAS_VERSION}_linux_amd64.tar.gz" oras
          ./oras pull ghcr.io/kjdev/oidc-provider-stub:static
          chmod 755 ./oidc-provider-stub
          nohup ./oidc-provider-stub php-server --listen :8888 > /dev/null 2>&1 &
          timeout 30 sh -c "while ! nc -z localhost 8888; do sleep 1; done"
          if [ $? -eq 124 ]; then
            echo "Timeout: Port 8888 was not opened within 30 seconds."
            exit 1
          fi
          echo "::endgroup::"
          # Run Redis
          echo "::group::run redis"
          redis-server --daemonize yes
          echo "::endgroup::"
          # Run test
          export TEST_NGINX_CONF_DIR="${PWD}/t/conf"
          prove -r t
        env:
          ORAS_VERSION: 1.3.1
          OIDC_CLIENT_ID: test
          OIDC_CLIENT_SECRET: b028e7a42bbb072acf09ed342e760627
          OIDC_REDIRECT_URI: http://127.0.0.1:1984/oidc_callback
          TEST_NGINX_LOAD_MODULES: /usr/lib/nginx/modules/ngx_http_oidc_module.so /usr/lib/nginx/modules/ndk_http_module.so /usr/lib/nginx/modules/ngx_http_lua_module.so
          TEST_NGINX_LUA_DIR: /usr/share/lua/5.1/
          TEST_NGINX_PORT: 1984
          TEST_NGINX_SERVROOT: /tmp/servroot
          TEST_NGINX_BINARY: /usr/local/sbin/nginx
    timeout-minutes: 30
    strategy:
      matrix:
        nginx:
          - alpine
          - ubuntu
          - '1.30.4' # stable
          - '1.31.4' # mainline
    container:
      image: ${{ matrix.nginx == 'alpine' && 'alpine:latest' || null }}
      options: ${{ matrix.nginx == 'alpine' && '--init' || null }}
